image: inovex/gitlab-ci-android

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - export BUILD_NUMBER=$(git rev-list --count ${CI_BUILD_REF})
  - export BUILD_COMMIT_SHA=${CI_COMMIT_SHA}
  - chmod +x ./gradlew

stages:
  - build
  - test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  script:
    - ./gradlew clean assembleDebug
  retry: 2
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${BUILD_NUMBER}"
    paths:
      - app/build/outputs/apk/*.apk
  only:
    - master

unitTest:
  stage: test
  script:
    - ./gradlew testDebugUnitTest --continue
  artifacts:
    paths:
      - core-network/build/reports/tests/**
      - app/build/reports/tests/**
