image: androidsdk/android-30

pipelines:
  default:
    - step:
        name: Initial work
        script:
          - chmod +x ./gradlew
    - step:
        name: Android Debug Application
        caches:
          - gradle
        script:
          - ./gradlew assembleDebug
        artifacts:
          - app/build/outputs/**