image: anthonymonori/android-ci-image:v1.2.1

pipelines:
  default:
    - step:
        name: Initial work
        script:
          - chmod +x ./gradlew
          - ./gradlew clean
    - step:
        name: Android Debug Application
        caches:
          - gradle
        script:
          - ./gradlew assembleRelease
        artifacts:
          - app/build/outputs/**