image: softartdev/android-fastlane

pipelines:
  default:
    - step:
        name: Initial work
        script:
          - chmod +x ./gradlew
          - ./gradlew clean
    - step:
        name: Android Debug Application
        caches:
          - gradle
        script:
          - ./gradlew assembleRelease
        artifacts:
          - app/build/outputs/**