image: softartdev/android-fastlane

pipelines:
  default:
    - step:
        name: Initial work
        script:
          - export ANDROID_KEYSTORE_FILE="$ANDROID_KEYSTORE_FILE"
          - export KEYSTORE_KEY_ALIAS="$KEYSTORE_KEY_ALIAS"
          - export KEYSTORE_KEY_PASSWORD="$KEYSTORE_KEY_PASSWORD"
          - export KEYSTORE_STORE_PASSWORD="$KEYSTORE_STORE_PASSWORD"
          - export SERVICE_CREDENTIALS="$SERVICE_CREDENTIALS"
          - chmod +x ./gradlew
    - step:
        name: Configure Keystore
        script:
          - echo "$ANDROID_KEYSTORE_FILE" > MyApp-release-key.jks.b64
          - base64 -d -i MyApp-release-key.jks.b64 > app/MyApp-release-key.jks
          - echo -e "storePassword=$KEYSTORE_STORE_PASSWORD\nkeyPassword=$KEYSTORE_KEY_PASSWORD\nkeyAlias=$KEYSTORE_KEY_ALIAS\nstoreFile=MyApp-release-key.jks" > keystore.properties
          - cat keystore.properties
          - echo "$SERVICE_CREDENTIALS" > fastlane_service_credentials.json
#    - step:
#        name: Upload Apk to Firebase
#        script:
#          - gem install bundler
#          - bundle install
#          - bundle exec fastlane distribute