image: softartdev/android-fastlane

pipelines:
  default:
    - step:
        name: Initial work
        script:
          - chmod +x ./gradlew
    - step:
        name: Upload Apk to Firebase
        script:
          - gem install bundler
          - bundle install
          - bundle exec fastlane distribute