# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
PROJECT_DIR = "D:\\AndroidProjects\\Learning\\LearningAndroidCustomCalendarKulakov\\"
APP_ID = "1:484548702433:android:d69157f00ede3715ac07a0"

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  lane :increment_version do
    latest_release = firebase_app_distribution_get_latest_release(
      app: APP_ID,
      service_credentials_file: "#{PROJECT_DIR}fastlane-test-b13ea-firebase-adminsdk-aiwqb-aae98ba9af.json"
    )
    increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
  end

  desc "Distribute app to Firebase"
  lane :distribute do
      increment_version
      gradle(task: "clean assembleRelease")
      # build_android_app is a built-in fastlane action.
      release = firebase_app_distribution(
          app: APP_ID,
          service_credentials_file: "#{PROJECT_DIR}fastlane-test-b13ea-firebase-adminsdk-aiwqb-aae98ba9af.json",
          testers_file: "#{PROJECT_DIR}testers.txt",
          release_notes_file: "#{PROJECT_DIR}release_notes.txt"
      )
  end
end
