# Github action to build and upload the apk on firebase app distribution when any feature branch merge in fastlane-with-github-action branch

name: Create and Upload Apk on Firebase App Distribution.

on:
  push:
    branches: [ master ]

jobs:
  CI-Prod:
    name: Apk uploading on Firebase App Distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: oracle

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.1'

      - name: Install bundler
        run: |
          gem install bundler
          bundle install

      - name: Make gradlew executable
        run: |
          chmod +x ./gradlew

      - name: Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > MyApp-release-key.jks.b64
          base64 -d -i MyApp-release-key.jks.b64 > app/MyApp-release-key.jks
          echo -n "storeFile=MyApp-release-key.jks" >> keystore.properties
          echo -n "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo -n "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo -n "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

      - name: Upload Apk to Firebase
        run: bundle exec fastlane distribute
        env:
          APP_ID: ${{ secrets.APP_ID }}
