# Github action to build and upload the apk on firebase app distribution when any feature branch merge in fastlane-with-github-action branch

name: Create and Upload Apk on Firebase App Distribution.

on:
  push:
    branches: [ fastlane-with-github-action ]

jobs:
  # Job 1 ->
  CI-Prod:
    name: Apk uploading on Firebase App Distribution
    runs-on: ubuntu-latest

    steps:
      # Step 2 Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 3 Setup JDK
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Step 4 Setup Ruby
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      # Step 5 Install the bundler & Fastlane (Create environment for ruby to avoid dependency hell and manage the dependencies versions)
      - name: Install bundler
        run: |
          gem install bundler:2.2.27
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # Step 6 Install the Firebase app distribution plugin with fastlane
      - name: Install Firebase app distribution plugin
        run: bundle exec fastlane add_plugin firebase_app_distribution

      # Step 10 Run the fastlane command to upload the build
      - name: Upload Apk to Firebase
        run: bundle exec fastlane distribute
